# To see the compatibility of other versions: https://github.com/JanusGraph/janusgraph/releases
version: "3.7"

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    environment:
      CASSANDRA_START_RPC: "true"
    ports:
      - "9160:9160"
      - "9042:9042"
      - "7199:7199"
      - "7001:7001"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - jce-network
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "cluster.name=docker-cluster"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    ports:
      - "9200:9200"
    networks:
      - jce-network
  janusgraph:
    container_name: janusgraph
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8182:8182"
    networks:
      - jce-network
    depends_on:
      - elasticsearch
      - cassandra

networks:
  jce-network:
volumes:
  janusgraph-default-data:
